### PR TITLE
added some features and fixed Dockerfile

### PR DESCRIPTION
**Pull request by jlinkohr**
Great Applicatipon ! 
I fixed one issue in the dockerfile and added bearer token usage (as we need this for our datacenter instance of Jira. also added the feature of only storing the gv file without using the google API.
If you like this, please add it to the repo!

### CODE REVIEW

**Comment by zarifpour** [comment]
Awesome, thank you!

I'll take a look at it tonight.

**Comment by zarifpour** [comment]
Thanks for fixing the issue.
- I refactored the code a bit to modularize the methods for saving graphs
- I also added a flag for PNG only
- I modified the shorter graphviz only flag from `-g` to `-gv`
Cheers 🍻

**Comment by jlinkohr** [comment]
yes, this improves definetely the code quality :)  thanks!
I have some ideas and maybe there will be more features around the program coming soon shall I open issues for that or just suggest the change if it is done? 
e.g. having one dockerfile that contains the script, gv and a small flask wrapper. If this is running somewhere, you can "embedd" the link in every jira ticket you are using and have an ad-hoc graph.

**Comment by zarifpour** [comment]
either way works. 
you can open an issue, to add it to the backlog, or you can submit a PR if it's done.

sound cool :)

**Pull request merged**
